### ISSUE TITLE
好像没有浓度预测部分代码耶？

### ISSUE THREAD

**Issue by gw-zhong** [Popsama/An-adaptively-optimized-gas-analysis-model-#1]
首先谢谢你可以开源代码和分享数据！但是是不是少了些代码？测试里面也只有涉及滤波模型的测试，好像并没有浓度预测的部分？还有一个问题就是，论文里说数据取的是0-1000ppm，那么区间的开闭是怎样的？因为给出的模拟数据只有1000个样本，所以不确定是[0, 999]还是[1, 1000]这样。

**Comment by Popsama** [comment]
1到1000的闭区间。只涉及滤波性能的测试结果可能是因为我们的重点是在滤波上。也可能是当时确实遗漏了ncr浓度反演的部分。谢谢提醒，我需要重新审核一遍代码，并考虑后续添加上去。最近有几篇论文要投稿，毕业论文要写，还要找博士后工作，实在太忙。
Linbo


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年1月25日 01:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1) |

首先谢谢你可以开源代码和分享数据！但是是不是少了些代码？测试里面也只有涉及滤波模型的测试，好像并没有浓度预测的部分？还有一个问题就是，论文里说数据取的是0-1000ppm，那么区间的开闭是怎样的？因为给出的模拟数据只有1000个样本，所以不确定是[0, 999]还是[1, 1000]这样。

**Comment by Popsama** [comment]
事实上模拟投射光谱或者吸光度谱实现模拟数据集的构建工作是很容易的。所以你其实不用太纠结浓度范围。如果你的模型期望检测的浓度范围是ppb级别（相比我们的ppm的检测范围），或者是其他范围（5%上下？），你完全可以让模型在trace level或者其他尺度上去拟合。祝科研顺利。
Linbo



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年1月25日 01:38 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1) |

首先谢谢你可以开源代码和分享数据！但是是不是少了些代码？测试里面也只有涉及滤波模型的测试，好像并没有浓度预测的部分？还有一个问题就是，论文里说数据取的是0-1000ppm，那么区间的开闭是怎样的？因为给出的模拟数据只有1000个样本，所以不确定是[0, 999]还是[1, 1000]这样。

**Comment by 32565** [comment]
作者可否公开浓度反演部分代码，谢谢！

**Comment by Popsama** [comment]
我最近在忙毕业论文和其他事，你等我有空了再上传吧 好么。 真是累吐了最近，昨天还收到其他仓库的issue然后给update了一下。
让我先把毕业论文和项目申请搞完吧（哭哭）


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年3月26日 21:44 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1) |

作者可否公开浓度反演部分代码，谢谢！

**Comment by 32565** [comment]
您先忙，毕业顺利哟😊😊😊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1)




 我最近在忙毕业论文和其他事，你等我有空了再上传吧 好么。 真是累吐了最近，昨天还收到其他仓库的issue然后给update了一下。
 让我先把毕业论文和项目申请搞完吧（哭哭）
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 发送日期 | 2023年3月26日 21:44 |
 | 收件人 | ***@***.***&gt; |
 | 抄送人 | ***@***.***&gt; ,
 ***@***.***&gt; |
 | 主题 | Re: [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1) |
 
 作者可否公开浓度反演部分代码，谢谢！

**Comment by gw-zhong** [comment]
田同学你好，我注意到使用您的compute_snr()函数在模拟数据下计算出的SNR值出现大量的负数（如下图所示），请问这是合理的吗？（信号学小白，望理解
![图片](https://github.com/Popsama/An-adaptively-optimized-gas-analysis-model-/assets/61236543/c9b5492c-3bf3-42b6-a15b-2d9cf22a1fee)

**Comment by Popsama** [comment]
是合理的 有可能出现这个情况，根据代码里的信噪比公式，出现负数情况代表的意思是“信号”对“噪声”的比值小于1，因此取Log之后会小于0，正常的，我记得我们实验的时候 训练早期因为模型的滤波效果较差，会出现这种情况

**Comment by Popsama** [comment]
> 田同学你好，我注意到使用您的compute_snr()函数在模拟数据下计算出的SNR值出现大量的负数（如下图所示），请问这是合理的吗？（信号学小白，望理解 ![图片](https://user-images.githubusercontent.com/61236543/242021447-c9b5492c-3bf3-42b6-a15b-2d9cf22a1fee.png)

之后我上传一下浓度反演的部分

**Comment by Popsama** [comment]
> 田同学你好，我注意到使用您的compute_snr()函数在模拟数据下计算出的SNR值出现大量的负数（如下图所示），请问这是合理的吗？（信号学小白，望理解 ![图片](https://user-images.githubusercontent.com/61236543/242021447-c9b5492c-3bf3-42b6-a15b-2d9cf22a1fee.png)

是合理的 有可能出现这个情况，根据代码里的信噪比公式，出现负数情况代表的意思是“信号”对“噪声”的比值小于1，因此取Log之后会小于0，正常的，我记得我们实验的时候 训练早期因为模型的滤波效果较差，会出现这种情况

**Comment by Popsama** [comment]
> 

之后我上传一下浓度反演的部分

**Comment by Popsama** [comment]
> 您先忙，毕业顺利哟😊😊😊
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年3月28日(周二) 中午11:19 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1) 我最近在忙毕业论文和其他事，你等我有空了再上传吧 好么。 真是累吐了最近，昨天还收到其他仓库的issue然后给update了一下。 让我先把毕业论文和项目申请搞完吧（哭哭）
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***&gt; | | 发送日期 | 2023年3月26日 21:44 | | 收件人 | ***@***.***&gt; | | 抄送人 | ***@***.***&gt; , ***@***.***&gt; | | 主题 | Re: [Popsama/An-adaptively-optimized-gas-analysis-model-] 好像没有浓度预测部分代码耶？ (Issue #1) | 作者可否公开浓度反演部分代码，谢谢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt; — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

之后我上传一下浓度反演的部分
